//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN.Services.NetworkModelService.DataModel.Ostale
{
    using System;
    using System.Collections.Generic;
    using FTN;
    using FTN.Common;
    using FTN.Services.NetworkModelService.DataModel.Core;


    /// A Series Compensator is a series capacitor or reactor or an AC transmission line without charging susceptance.  It is a two terminal device.
    public class SeriesCompensator : ConductingEquipment
    {
        public SeriesCompensator(long globalId) : base(globalId) { }

        private float r;

        public float R
        {
            get { return r; }
            set { r = value; }
        }
        private float r0;

        public float R0
        {
            get { return r0; }
            set { r0 = value; }
        }

        private float x;

        public float X
        {
            get { return x; }
            set { x = value; }
        }
        private float x0;

        public float X0
        {
            get { return x0; }
            set { x0 = value; }
        }

        public override bool Equals(object x)
        {
            if (base.Equals(x))
            {
                SeriesCompensator obj = (SeriesCompensator)x;
                return this.r == obj.r &&
                       this.r0 == obj.r0 &&
                       this.x == obj.x &&
                       this.x0 == obj.x0;
            }
            else
            {
                return false;
            }
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        #region IAccess Implementation

        public override bool HasProperty(ModelCode property)
        {
            switch (property)
            {
                case ModelCode.SERIES_COMP_R:
                case ModelCode.SERIES_COMP_X:
                case ModelCode.SERIES_COMP_X0:
                case ModelCode.SERIES_COMP_R0:
                    return true;
                default:
                    return base.HasProperty(property);
            }
        }

        public override void GetProperty(Property property)
        {
            switch (property.Id)
            {
                case ModelCode.SERIES_COMP_X:
                    property.SetValue(this.X);
                    break;
                case ModelCode.SERIES_COMP_X0:
                    property.SetValue(this.X0);
                    break;
                case ModelCode.SERIES_COMP_R:
                    property.SetValue(this.R);
                    break;
                case ModelCode.SERIES_COMP_R0:
                    property.SetValue(this.R0);
                    break;
                default:
                    base.GetProperty(property);
                    break;
            }
        }

        public override void SetProperty(Property property)
        {
            switch (property.Id)
            {
                case ModelCode.SERIES_COMP_X:
                    this.X = property.AsFloat();
                    break;
                case ModelCode.SERIES_COMP_X0:
                    this.X0 = property.AsFloat();
                    break;
                case ModelCode.SERIES_COMP_R:
                    this.R = property.AsFloat();
                    break;
                case ModelCode.SERIES_COMP_R0:
                    this.R0 = property.AsFloat();
                    break;
                default:
                    base.SetProperty(property);
                    break;
            }
        }


        #endregion

        #region IReference


        public override void GetReferences(Dictionary<ModelCode, List<long>> references, TypeOfReference refType)
        {
            base.GetReferences(references, refType);
        }

        public override void AddReference(ModelCode referenceId, long globalId)
        {

            base.AddReference(referenceId, globalId);

        }

        public override void RemoveReference(ModelCode referenceId, long globalId)
        {

            base.RemoveReference(referenceId, globalId);

        }

        #endregion
    }
}
